#!/bin/bash
NAME=jbec
function ba {
	mkdir -p prcpp-week0$n-$NAME/src
	mkdir -p prcpp-week0$n-$NAME/results
	mkdir -p prcpp-week0$n-$NAME/graphs
	find prcpp-week0$n -name "*.java" | xargs -I{} cp {} ./prcpp-week0$n-$NAME/src/
	find prcpp-week0$n -not -name "answers.txt" -name "*.txt" | xargs -I{} cp {} ./prcpp-week0$n-$NAME/results/
	find prcpp-week0$n -name "*.xlsx"  | xargs -I{} cp {} ./prcpp-week0$n-$NAME/graphs
	find prcpp-week0$n -name "answers.txt"  | xargs -I{} cp {} ./prcpp-week0$n-$NAME/
	find ./prcpp-week0$n-$NAME -maxdepth 1 -name "*.txt" | xargs -I{} zip -m prcpp-week0$n-$NAME.zip {}
	find ./prcpp-week0$n-$NAME/graphs -maxdepth 1 -name "*.xlsx" | xargs -I{} zip -m prcpp-week0$n-$NAME.zip {}
	find ./prcpp-week0$n-$NAME/src -maxdepth 1 -name "*.java"  | xargs -I{} zip -m prcpp-week0$n-$NAME.zip {}
	find ./prcpp-week0$n-$NAME/results -maxdepth 1 -name "*.txt"  | xargs -I{} zip -m prcpp-week0$n-$NAME.zip {}
}
	rm -r prcpp-week0$n-$NAME
case "$1" in

	clean)
		rm -f -r *-$NAME*
		;;

        [1-9])
                if [ -d "prcpp-week0$1" ]; then
			ba $1
                else
                        echo "prcpp-week0$1 is not a valid directory"
                fi
		;;
	*)
		for n in {1..10} 	
		do
			if [ -d "prcpp-week0$n" ]; then
				ba $1
			else
				break	
			fi
		done
		;;
esac
