TestAccounts.class: TestAccounts.java 
	javac -cp ~/.lib/multiverse-core-0.7.0.jar TestAccounts.java
TestStmHistogram.class: TestStmHistogram.java
	javac -cp ~/.lib/multiverse-core-0.7.0.jar TestStmHistogram.java
clean:
	rm -rf *.class
