TestCasHistogram.class: TestCasHistogram.java Mark.java
	javac -cp ~/.lib/multiverse-core-0.7.0.jar TestCasHistogram.java Mark.java
TestSimpleRWTryLock.class: TestSimpleRWTryLock.java
	javac TestSimpleRWTryLock.java
clean:
	rm -rf *.class
